import type { Player } from "@/lib/types";

/**
 * Mock dataset for the public leaderboard.
 */
export const mockPlayers: Player[] = [
  {
    id: "akali-001",
    name: "AkaliSensei",
    role: "Mid",
    tier: "Esmeralda",
    division: "II",
    lp: 54,
    wins: 126,
    losses: 98,
    peakRank: "Diamante IV",
    lastUpdated: "2026-01-28",
    notes: "Racha positiva en la última semana.",
    objective: "Diamante III",
    monthCheckpoint: "En progreso",
    opggUrl: "https://www.op.gg/summoners/euw/AkaliSensei",
  },
  {
    id: "jinx-002",
    name: "JinxMain",
    role: "ADC",
    tier: "Platino",
    division: "I",
    lp: 72,
    wins: 93,
    losses: 74,
    peakRank: "Platino I",
    lastUpdated: "2026-01-30",
    notes: "Priorizar dúo bot.",
    objective: "Esmeralda IV",
    monthCheckpoint: "Fuerte",
    opggUrl: "https://www.op.gg/summoners/na/JinxMain",
  },
  {
    id: "ornn-003",
    name: "OrnnGuardian",
    role: "Top",
    tier: "Oro",
    division: "II",
    lp: 12,
    wins: 58,
    losses: 61,
    peakRank: "Oro I",
    lastUpdated: "2026-01-27",
    notes: "Mejorar macro y TP.",
    objective: "Platino IV",
    monthCheckpoint: "Estable",
    opggUrl: "https://www.op.gg/summoners/euw/OrnnGuardian",
  },
  {
    id: "lulu-004",
    name: "LuluShield",
    role: "Supp",
    tier: "Plata",
    division: "I",
    lp: 88,
    wins: 41,
    losses: 39,
    peakRank: "Plata I",
    lastUpdated: "2026-01-29",
    notes: "Priorizar visión en río.",
    objective: "Oro IV",
    monthCheckpoint: "En progreso",
    opggUrl: "https://www.op.gg/summoners/na/LuluShield",
  },
];
